paths:
    data:
        bronze: data/bronze
        silver: data/silver
        gold: data/gold

artifacts:
    data: 
        bronze: 
            issue: bronze_jira_issues_raw.json
        silver:
            issue: silver_jira_issues.parquet
            project: silver_jira_projects.parquet
        gold:
            issue: gold_jira_issues.parquet
            project: gold_jira_projects.parquet

source:
    account_url: https://stfasttracksdev.blob.core.windows.net
    container_name: source-jira
    blob_name: jira_issues_raw.json
